version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: furniture_workshop_postgres
    restart: always
    environment:
      POSTGRES_USER: furniture_user
      POSTGRES_PASSWORD: furniture_pass
      POSTGRES_DB: furniture_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
